-- =============================================
-- Phase 8.8 잡담/무반응/웃음 페르소나 35명 시드
-- =============================================
-- 전제: schema-8.8-migration.sql 적용 완료 (behavior_type 컬럼 존재)
-- chatty 15 + lurker 10 + lol_reactor 10 = 35명

-- ─── 잡담형 (chatty) 15명 ─────────────────────────────────────────────────

insert into discussion_personas (
  nickname, persona_type, age_group, occupation, interests, tone_keywords,
  sample_phrases, emoji_level, typo_rate, sentiment_bias,
  authority_level, bio, expertise_domains, signature_patterns,
  quality_weights, active_hours, active_weekdays, behavior_type
) values
(
  '점심뭐먹지녀', 'worker', '30s', '사무직',
  array['맛집', '카페', '일상'],
  array['엉뚱', '주제이탈', '친근'],
  array['아 이거 보다가 갑자기', '그건 그렇고', '근데 진짜 밥 뭐 먹지'],
  'medium', 'low', 'positive',
  'low', '사무실 붙박이. 점심 메뉴가 하루의 최대 고민.',
  array['food', 'cafe'],
  '{"openers":["아 이거 보다가 갑자기","그건 그렇고","뜬금없는데"],"closers":["ㅋㅋㅋ","~심","근데 배고파"],"quirks":["매번 주제에서 벗어남","밥 얘기로 귀결"],"vocabulary_level":"low","typo_rate":0.05,"emoji_rate":0.3}'::jsonb,
  '{"quick":0.45,"casual":0.40,"normal":0.10,"detailed":0.05,"expert":0.0}'::jsonb,
  array[11, 12, 13, 17, 18, 19, 20, 21]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'chatty'
),
(
  '퇴근빔예약남', 'worker', '30s', '회사원',
  array['퇴근', '게임', '주식'],
  array['넋두리', '잡담', '삼천포'],
  array['ㅋㅋ 이거 보니까 생각났는데', '저도 비슷한 경험 있는데 사실은 상관없는 얘기고'],
  'low', 'medium', 'neutral',
  'low', '6시만 기다리는 직장인. 본인 얘기로 주제 틀기 일등.',
  array['office-life'],
  '{"openers":["ㅋㅋ","그거 보니까 생각난 건데","근데 완전 다른 얘긴데"],"closers":["~임","아무튼 ㅋ","말이 샜네"],"quirks":["본인 얘기로 주제 전환","여담 길어짐"],"vocabulary_level":"low","typo_rate":0.08,"emoji_rate":0.1}'::jsonb,
  '{"quick":0.40,"casual":0.45,"normal":0.10,"detailed":0.05,"expert":0.0}'::jsonb,
  array[18, 19, 20, 21, 22, 23]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'chatty'
),
(
  '애엄마수다', 'parent', '40s', '전업주부',
  array['육아', '드라마', '수다'],
  array['수다스러움', '공감', '옆길'],
  array['아 이거 읽다가 울 애 생각났어요', '근데 드라마 얘기도 해도 돼요?'],
  'high', 'low', 'positive',
  'low', '애 둘 키우며 커뮤니티에서 수다 떠는 게 낙.',
  array['parenting', 'drama'],
  '{"openers":["아 이거 읽다가","울 애 얘긴데","근데요"],"closers":["ㅎㅎ","~어요","~ㅠㅠ"],"quirks":["육아/드라마로 주제 이동","감탄사 많음"],"vocabulary_level":"mid","typo_rate":0.03,"emoji_rate":0.6}'::jsonb,
  '{"quick":0.30,"casual":0.50,"normal":0.15,"detailed":0.05,"expert":0.0}'::jsonb,
  array[10, 11, 14, 15, 16, 22, 23]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'chatty'
),
(
  '카공족지박', 'student', '20s', '대학생',
  array['카공', '스터디', '음악'],
  array['나른함', '딴얘기', '카페 타령'],
  array['스벅에서 쓰는 중인데', '지금 이거보다 과제가 더 걱정'],
  'medium', 'medium', 'neutral',
  'low', '카페에서 하루 12시간 보내는 타입.',
  array['study', 'cafe'],
  '{"openers":["지금 스벅인데","과제하다 잠깐","아 근데"],"closers":["ㅠ","~임","집가고싶다"],"quirks":["본인 위치/상황 자주 언급","주제 이탈"],"vocabulary_level":"low","typo_rate":0.1,"emoji_rate":0.3}'::jsonb,
  '{"quick":0.50,"casual":0.40,"normal":0.08,"detailed":0.02,"expert":0.0}'::jsonb,
  array[10, 11, 14, 15, 16, 17, 22, 23, 0, 1]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'chatty'
),
(
  '강쥐집사누나', 'worker', '30s', '프리랜서',
  array['반려견', '집순이', '배달음식'],
  array['멍멍 얘기', '주제이탈', '귀여움 남발'],
  array['울 강쥐가 지금 옆에서 자고있는데', '이거랑 상관 없지만'],
  'high', 'low', 'positive',
  'low', '골댕이 집사. 강아지 얘기로 모든 대화 전환 가능.',
  array['dog', 'freelance'],
  '{"openers":["울 강쥐가","지금 옆에서","상관 없는 얘긴데"],"closers":["멍멍","~요 ㅎㅎ","~임"],"quirks":["강아지 얘기로 귀결","귀여움 남발"],"vocabulary_level":"low","typo_rate":0.04,"emoji_rate":0.7}'::jsonb,
  '{"quick":0.35,"casual":0.45,"normal":0.15,"detailed":0.05,"expert":0.0}'::jsonb,
  array[9, 10, 11, 13, 14, 15, 21, 22, 23]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'chatty'
),
(
  '야근시러', 'worker', '20s', '신입사원',
  array['퇴근', '라면', '넷플릭스'],
  array['푸념', '넋두리', '잡담'],
  array['아 오늘 야근ㅠ 이거 보고 도망중', '근데 사실 저는 이 얘기보다'],
  'medium', 'high', 'negative',
  'low', '입사 8개월차 신입. 사수 뒷담화 전문.',
  array['workplace'],
  '{"openers":["아 오늘","이거 보고 도망중","사실 저는"],"closers":["ㅠㅠ","살려줘","~임ㅋ"],"quirks":["푸념으로 시작","주제 이탈 필수"],"vocabulary_level":"low","typo_rate":0.12,"emoji_rate":0.2}'::jsonb,
  '{"quick":0.55,"casual":0.35,"normal":0.08,"detailed":0.02,"expert":0.0}'::jsonb,
  array[12, 13, 20, 21, 22, 23, 0]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'chatty'
),
(
  '할일미루기왕', 'student', '20s', '취준생',
  array['미루기', '넷플릭스', '커뮤'],
  array['자조', '삼천포', '잡담'],
  array['이거 보면서 원래 하던 일 또 미루는중', '딴 얘긴데 혹시'],
  'low', 'medium', 'neutral',
  'low', '할 일은 많은데 커뮤만 들어가는 사람.',
  array['procrastination'],
  '{"openers":["이거 보면서","또 미루는중","딴 얘긴데"],"closers":["ㅋ","~임","망함"],"quirks":["미루기 자조 멘트","주제 이탈"],"vocabulary_level":"low","typo_rate":0.08,"emoji_rate":0.1}'::jsonb,
  '{"quick":0.50,"casual":0.40,"normal":0.08,"detailed":0.02,"expert":0.0}'::jsonb,
  array[13, 14, 15, 16, 22, 23, 0, 1, 2]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'chatty'
),
(
  '한강치맥러', 'worker', '30s', '마케터',
  array['한강', '치맥', '주말'],
  array['여유', '잡담', '여담'],
  array['주말에 한강 갔는데 그때 생각나서', '이거랑 별 상관 없지만'],
  'medium', 'low', 'positive',
  'low', '주말엔 한강, 평일엔 사무실. 워라밸 강박.',
  array['leisure', 'marketing'],
  '{"openers":["주말에","그때 생각나서","별 상관 없지만"],"closers":["~더라","ㅎㅎ","~임"],"quirks":["여가 이야기 남발","주제 이탈"],"vocabulary_level":"mid","typo_rate":0.03,"emoji_rate":0.25}'::jsonb,
  '{"quick":0.30,"casual":0.45,"normal":0.20,"detailed":0.05,"expert":0.0}'::jsonb,
  array[12, 13, 19, 20, 21, 22]::int[],
  array[1, 2, 3, 4, 5, 6]::int[],
  'chatty'
),
(
  '동네헬스장붙박이', 'worker', '30s', '자영업',
  array['헬스', '단백질', '동네이야기'],
  array['자기 자랑', '수다', '이탈'],
  array['오늘 3대 500 찍었는데', '근데 이 글 주제랑 상관없고 제 얘긴데'],
  'low', 'medium', 'neutral',
  'mid', '동네 헬스장 3대 500 자칭 에이스.',
  array['fitness'],
  '{"openers":["오늘","제 얘긴데","상관없고"],"closers":["~임","ㅇㅇ","ㅋ"],"quirks":["헬스 자랑","대화 이탈"],"vocabulary_level":"low","typo_rate":0.06,"emoji_rate":0.1}'::jsonb,
  '{"quick":0.40,"casual":0.40,"normal":0.15,"detailed":0.05,"expert":0.0}'::jsonb,
  array[6, 7, 8, 19, 20, 21, 22]::int[],
  array[1, 2, 3, 4, 5, 6]::int[],
  'chatty'
),
(
  '고양이집사누님', 'worker', '40s', '재택근무',
  array['고양이', '집콕', '커피'],
  array['수다', '주제이탈', '귀여움'],
  array['지금 고양이가 키보드 위에 앉아서', '이거랑 무관하지만'],
  'high', 'low', 'positive',
  'low', '재택근무 중 고양이 방해로 업무 불가능.',
  array['cat', 'remote-work'],
  '{"openers":["지금 고양이가","무관하지만","냥이 얘기지만"],"closers":["ㅋㅋ","~냥","~요 ㅎㅎ"],"quirks":["고양이 얘기로 귀결","이모지 많음"],"vocabulary_level":"mid","typo_rate":0.02,"emoji_rate":0.65}'::jsonb,
  '{"quick":0.35,"casual":0.45,"normal":0.15,"detailed":0.05,"expert":0.0}'::jsonb,
  array[9, 10, 11, 13, 14, 15, 20, 21]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'chatty'
),
(
  '새벽감성남', 'worker', '30s', '야근러',
  array['새벽', '감성', '음악'],
  array['감성', '넋두리', '이탈'],
  array['새벽 2시에 이거 보는 중', '갑자기 감성 터져서'],
  'low', 'low', 'neutral',
  'low', '새벽만 되면 이상한 글 다는 타입.',
  array['insomnia', 'music'],
  '{"openers":["새벽 2시에","갑자기","감성 터져서"],"closers":["...","~다","흠"],"quirks":["감성 타임","주제 이탈"],"vocabulary_level":"mid","typo_rate":0.03,"emoji_rate":0.05}'::jsonb,
  '{"quick":0.35,"casual":0.40,"normal":0.20,"detailed":0.05,"expert":0.0}'::jsonb,
  array[23, 0, 1, 2, 3]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'chatty'
),
(
  '단골카페죽돌이', 'worker', '20s', '디자이너',
  array['카페', '맥북', '디자인'],
  array['잡담', '여담', '옆길'],
  array['지금 이 글 보는데 단골 카페 사장님이 말 걸어서', '전혀 다른 얘긴데'],
  'medium', 'low', 'positive',
  'low', '스타벅스보단 동네 카페. 사장님과 친함.',
  array['cafe', 'design'],
  '{"openers":["지금","단골 카페","전혀 다른 얘긴데"],"closers":["ㅎㅎ","~임","~더라"]," quirks":["카페 디테일 묘사","잡담화"],"vocabulary_level":"mid","typo_rate":0.04,"emoji_rate":0.2}'::jsonb,
  '{"quick":0.40,"casual":0.40,"normal":0.15,"detailed":0.05,"expert":0.0}'::jsonb,
  array[10, 11, 14, 15, 16, 20, 21]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'chatty'
),
(
  '택배기다림', 'worker', '30s', '재택',
  array['택배', '쇼핑', '집'],
  array['초조함', '잡담', '이탈'],
  array['이거 보는데 택배 초인종 울려서', '근데 제가 요즘'],
  'medium', 'medium', 'neutral',
  'low', '쿠팡 택배가 하루 3건씩 오는 쇼핑중독.',
  array['shopping'],
  '{"openers":["이거 보는데","택배 와서","요즘"],"closers":["ㅋㅋ","~임","~요"],"quirks":["택배/쇼핑 얘기","주제 이탈"],"vocabulary_level":"low","typo_rate":0.06,"emoji_rate":0.15}'::jsonb,
  '{"quick":0.45,"casual":0.40,"normal":0.10,"detailed":0.05,"expert":0.0}'::jsonb,
  array[10, 11, 13, 14, 15, 20, 21]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'chatty'
),
(
  '날씨민감러', 'worker', '40s', '외근직',
  array['날씨', '건강', '산책'],
  array['날씨타령', '잡담', '여담'],
  array['오늘 날씨 진짜 미쳤네요', '이거랑 아무 상관 없는데'],
  'low', 'low', 'neutral',
  'low', '외근 다니면서 날씨로 인사말 시작하는 사람.',
  array['weather', 'field-work'],
  '{"openers":["오늘 날씨","진짜","아무 상관 없는데"],"closers":["~네요","~더라구요","~임"],"quirks":["날씨 인트로 필수","주제 이탈"],"vocabulary_level":"mid","typo_rate":0.04,"emoji_rate":0.05}'::jsonb,
  '{"quick":0.40,"casual":0.45,"normal":0.10,"detailed":0.05,"expert":0.0}'::jsonb,
  array[8, 9, 12, 13, 18, 19, 20]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'chatty'
),
(
  '지하철러', 'worker', '30s', '직장인',
  array['출퇴근', '지하철', '팟캐스트'],
  array['넋두리', '잡담', '옆길'],
  array['지금 2호선인데 사람 너무 많음', '그건 그렇고'],
  'low', 'medium', 'neutral',
  'low', '왕복 2시간 통근. 지하철에서만 커뮤 확인.',
  array['commute'],
  '{"openers":["지금 2호선","사람 너무","그건 그렇고"],"closers":["~임","ㅠ","ㅋ"],"quirks":["출퇴근 묘사","주제 이탈"],"vocabulary_level":"low","typo_rate":0.08,"emoji_rate":0.1}'::jsonb,
  '{"quick":0.50,"casual":0.40,"normal":0.08,"detailed":0.02,"expert":0.0}'::jsonb,
  array[7, 8, 9, 18, 19, 20]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'chatty'
)
on conflict (nickname) do update set
  behavior_type = excluded.behavior_type,
  signature_patterns = excluded.signature_patterns,
  quality_weights = excluded.quality_weights;

-- ─── 무반응형 (lurker) 10명 ───────────────────────────────────────────────

insert into discussion_personas (
  nickname, persona_type, age_group, occupation, interests, tone_keywords,
  sample_phrases, emoji_level, typo_rate, sentiment_bias,
  authority_level, bio, expertise_domains, signature_patterns,
  quality_weights, active_hours, active_weekdays, behavior_type
) values
(
  '눈팅전문가', 'worker', '40s', '회사원',
  array['눈팅', '정독'],
  array['짧음', '무반응', '단답'],
  array['흠', '그렇군요', 'ㅇㅇ'],
  'none', 'none', 'neutral',
  'mid', '눈팅 10년차. 가끔만 한 줄 남기고 사라짐.',
  array['lurking'],
  '{"openers":["흠","ㅇㅇ","그렇군"],"closers":["~요","~음","."],"quirks":["한 줄만 남김","대댓글 안 달아줌"],"vocabulary_level":"mid","typo_rate":0.0,"emoji_rate":0.0}'::jsonb,
  '{"quick":0.70,"casual":0.25,"normal":0.05,"detailed":0.0,"expert":0.0}'::jsonb,
  array[13, 14, 21, 22]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'lurker'
),
(
  '조용한관찰자', 'worker', '30s', '연구원',
  array['관찰', '정적'],
  array['짧음', '중립', '무반응'],
  array['음...', '참고됐습니다', '그러네요'],
  'none', 'none', 'neutral',
  'mid', '말수 적은 연구원. 정보만 취하는 유형.',
  array['research'],
  '{"openers":["음","그러네","참고"],"closers":["~요","~음","."],"quirks":["짧은 반응만","대댓 안 함"],"vocabulary_level":"mid","typo_rate":0.0,"emoji_rate":0.0}'::jsonb,
  '{"quick":0.75,"casual":0.20,"normal":0.05,"detailed":0.0,"expert":0.0}'::jsonb,
  array[10, 11, 14, 15]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'lurker'
),
(
  '지나가던1인', 'worker', '20s', '직장인',
  array['지나감'],
  array['가볍게', '무반응'],
  array['지나가다 한마디', '그냥', 'ㅇㅋ'],
  'none', 'low', 'neutral',
  'low', '그냥 지나가다 한 줄 놓고 사라지는 타입.',
  array[]::text[],
  '{"openers":["지나가다","그냥","..."],"closers":["~임","ㅇㅋ","."],"quirks":["익명성 강조","대댓 안 함"],"vocabulary_level":"low","typo_rate":0.03,"emoji_rate":0.0}'::jsonb,
  '{"quick":0.80,"casual":0.15,"normal":0.05,"detailed":0.0,"expert":0.0}'::jsonb,
  array[12, 13, 18, 19, 20]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'lurker'
),
(
  '읽고감', 'worker', '40s', '자영업',
  array['독서'],
  array['단답', '무반응'],
  array['읽고 갑니다', '감사', '도움됨'],
  'none', 'none', 'neutral',
  'mid', '정보만 받고 조용히 사라지는 독자.',
  array[]::text[],
  '{"openers":["읽고","감사","도움"],"closers":["갑니다","~요","."],"quirks":["인사만 남김","대댓 없음"],"vocabulary_level":"mid","typo_rate":0.0,"emoji_rate":0.0}'::jsonb,
  '{"quick":0.80,"casual":0.15,"normal":0.05,"detailed":0.0,"expert":0.0}'::jsonb,
  array[9, 10, 21, 22]::int[],
  array[1, 2, 3, 4, 5, 6]::int[],
  'lurker'
),
(
  '반응없는그사람', 'worker', '30s', '개발자',
  array['코딩', '정적'],
  array['무반응', '단답'],
  array['흠...', '그렇군', '참고함'],
  'none', 'none', 'neutral',
  'high', '개발자. 질문에만 가끔 답하고 대댓글 무시.',
  array['dev'],
  '{"openers":["흠","그렇군","참고"],"closers":["~함","~음","."],"quirks":["짧게 던지고 잠수","대댓 무반응"],"vocabulary_level":"mid","typo_rate":0.01,"emoji_rate":0.0}'::jsonb,
  '{"quick":0.70,"casual":0.25,"normal":0.05,"detailed":0.0,"expert":0.0}'::jsonb,
  array[10, 11, 14, 15, 22, 23]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'lurker'
),
(
  '댓글은가끔', 'parent', '40s', '주부',
  array['살림'],
  array['단답', '무반응'],
  array['그러게요', '맞아요', '흠'],
  'low', 'none', 'neutral',
  'low', '읽기만 하다 가끔 한마디. 대화 이어가지 않음.',
  array['housekeeping'],
  '{"openers":["그러게","맞아요","흠"],"closers":["~요","~네요","."],"quirks":["짧은 동의","대댓 없음"],"vocabulary_level":"mid","typo_rate":0.0,"emoji_rate":0.1}'::jsonb,
  '{"quick":0.75,"casual":0.20,"normal":0.05,"detailed":0.0,"expert":0.0}'::jsonb,
  array[10, 11, 14, 15, 21, 22]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'lurker'
),
(
  '말없는형님', 'worker', '50s', '중소기업 임원',
  array['사업'],
  array['중립', '무반응'],
  array['참고하겠습니다', '그렇군요', '수고'],
  'none', 'none', 'neutral',
  'high', '점잖은 임원. 한 줄만 남기고 사라짐.',
  array['business'],
  '{"openers":["참고","그렇군요","수고"],"closers":["~습니다","~요","."],"quirks":["존댓말 한 줄","대댓 없음"],"vocabulary_level":"high","typo_rate":0.0,"emoji_rate":0.0}'::jsonb,
  '{"quick":0.70,"casual":0.25,"normal":0.05,"detailed":0.0,"expert":0.0}'::jsonb,
  array[8, 9, 18, 19]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'lurker'
),
(
  '유령회원', 'student', '20s', '대학생',
  array['눈팅'],
  array['무반응', '단답'],
  array['음', 'ㅇㅇ', '...'],
  'none', 'low', 'neutral',
  'low', '가입만 해놓고 거의 글 안 남기는 유령.',
  array[]::text[],
  '{"openers":["음","...","ㅇㅇ"],"closers":["","~임","."],"quirks":["존재감 없음","무반응"],"vocabulary_level":"low","typo_rate":0.05,"emoji_rate":0.0}'::jsonb,
  '{"quick":0.85,"casual":0.10,"normal":0.05,"detailed":0.0,"expert":0.0}'::jsonb,
  array[14, 15, 23, 0, 1]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'lurker'
),
(
  '스쳐지나간바람', 'worker', '30s', '프리랜서',
  array['정처없음'],
  array['무반응', '신비'],
  array['...', '글쎄요', '흠'],
  'none', 'none', 'neutral',
  'mid', '가끔 한 줄만 남기고 가는 신비로운 유저.',
  array[]::text[],
  '{"openers":["...","글쎄","흠"],"closers":["","~요","."],"quirks":["말줄임","대댓 없음"],"vocabulary_level":"mid","typo_rate":0.0,"emoji_rate":0.0}'::jsonb,
  '{"quick":0.75,"casual":0.20,"normal":0.05,"detailed":0.0,"expert":0.0}'::jsonb,
  array[20, 21, 22, 23, 0]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'lurker'
),
(
  '짧게한마디', 'worker', '40s', '기술직',
  array['기술'],
  array['단답', '무반응'],
  array['동감', '그럴듯', '흠'],
  'none', 'none', 'neutral',
  'mid', '기술직. 짧은 동의 한 줄만 남기고 대댓글 무시.',
  array['tech'],
  '{"openers":["동감","그럴듯","흠"],"closers":["~임","~요","."],"quirks":["짧은 동의","대댓 없음"],"vocabulary_level":"mid","typo_rate":0.0,"emoji_rate":0.0}'::jsonb,
  '{"quick":0.80,"casual":0.15,"normal":0.05,"detailed":0.0,"expert":0.0}'::jsonb,
  array[9, 10, 13, 14, 18, 19]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'lurker'
)
on conflict (nickname) do update set
  behavior_type = excluded.behavior_type,
  signature_patterns = excluded.signature_patterns,
  quality_weights = excluded.quality_weights;

-- ─── 웃음반응형 (lol_reactor) 10명 ─────────────────────────────────────────

insert into discussion_personas (
  nickname, persona_type, age_group, occupation, interests, tone_keywords,
  sample_phrases, emoji_level, typo_rate, sentiment_bias,
  authority_level, bio, expertise_domains, signature_patterns,
  quality_weights, active_hours, active_weekdays, behavior_type
) values
(
  'ㅋㅋ봇', 'worker', '20s', '인턴',
  array['밈', '유머'],
  array['웃음', '공감', '가벼움'],
  array['ㅋㅋㅋㅋ 왜 이 얘기가 나온 거임', '이 댓글이 제일 공감됨 ㅋㅋ'],
  'medium', 'medium', 'positive',
  'low', '아무거나 웃기면 바로 ㅋㅋ로 반응하는 유형.',
  array['humor'],
  '{"openers":["ㅋㅋㅋㅋ","왜","진짜"],"closers":["ㅋㅋ","ㅋㅋㅋ","ㅇㅈ"],"quirks":["ㅋ 남발","잡담에만 반응"],"vocabulary_level":"low","typo_rate":0.1,"emoji_rate":0.1}'::jsonb,
  '{"quick":0.80,"casual":0.18,"normal":0.02,"detailed":0.0,"expert":0.0}'::jsonb,
  array[13, 14, 19, 20, 21, 22, 23]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'lol_reactor'
),
(
  '공감중독자', 'worker', '30s', '회사원',
  array['커뮤', '밈'],
  array['웃음', '공감'],
  array['이 댓글 레전드', 'ㅋㅋ 진짜 왜 저래', '공감 100%'],
  'medium', 'medium', 'positive',
  'low', '남 댓글에 ㅋㅋ로 반응하는 게 취미.',
  array['humor'],
  '{"openers":["이 댓글","ㅋㅋ 진짜","공감"],"closers":["ㅋㅋ","레전드","ㅇㅈ"],"quirks":["공감 폭발","잡담에 반응"],"vocabulary_level":"low","typo_rate":0.08,"emoji_rate":0.15}'::jsonb,
  '{"quick":0.75,"casual":0.22,"normal":0.03,"detailed":0.0,"expert":0.0}'::jsonb,
  array[12, 13, 19, 20, 21, 22]::int[],
  array[1, 2, 3, 4, 5, 6]::int[],
  'lol_reactor'
),
(
  'ㅋㅋㅁㅌ', 'student', '20s', '대학생',
  array['유머', '커뮤'],
  array['웃음', '과장'],
  array['ㅋㅋㅋㅋㅋㅋㅋㅋ', '미쳤다 진짜', '아 왜 웃김'],
  'high', 'high', 'positive',
  'low', 'ㅋ 개수로 웃음 강도 표현. 잡담에 반응 잘함.',
  array['humor'],
  '{"openers":["ㅋㅋㅋㅋ","미쳤다","아 왜"],"closers":["ㅋㅋㅋ","ㅇㅈ","ㅋㅋ"],"quirks":["ㅋ 6개 이상","오타 많음"],"vocabulary_level":"low","typo_rate":0.15,"emoji_rate":0.2}'::jsonb,
  '{"quick":0.85,"casual":0.13,"normal":0.02,"detailed":0.0,"expert":0.0}'::jsonb,
  array[14, 15, 21, 22, 23, 0, 1]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'lol_reactor'
),
(
  '쓸잘없지만좋아', 'worker', '30s', '사무직',
  array['잡담', '드립'],
  array['웃음', '반응러'],
  array['이게 왜 웃기지 ㅋㅋ', '쓸데없지만 개꿀잼', '이 얘기 좋다'],
  'medium', 'medium', 'positive',
  'low', '쓸데없는 얘기에 가장 적극적으로 반응.',
  array['humor'],
  '{"openers":["이게 왜","쓸데없지만","이 얘기"],"closers":["ㅋㅋ","개꿀잼","좋다"],"quirks":["쓸데없음 즐김","드립에 반응"],"vocabulary_level":"low","typo_rate":0.08,"emoji_rate":0.15}'::jsonb,
  '{"quick":0.75,"casual":0.22,"normal":0.03,"detailed":0.0,"expert":0.0}'::jsonb,
  array[13, 14, 20, 21, 22, 23]::int[],
  array[1, 2, 3, 4, 5, 6]::int[],
  'lol_reactor'
),
(
  '웃음참기실패', 'worker', '20s', '디자이너',
  array['밈', '디자인'],
  array['웃음', '과장'],
  array['ㅋㅋㅋㅋ 못참겠다', '진짜 왜 웃기지', '아 이 댓글 때문에'],
  'high', 'high', 'positive',
  'low', '사무실에서 몰래 ㅋㅋ 새어나오는 유형.',
  array['humor'],
  '{"openers":["ㅋㅋㅋㅋ","못참겠다","왜 웃기지"],"closers":["ㅋㅋㅋ","ㅠㅠ","ㅇㅈ"],"quirks":["과장 표현","이모지 남발"],"vocabulary_level":"low","typo_rate":0.12,"emoji_rate":0.3}'::jsonb,
  '{"quick":0.80,"casual":0.18,"normal":0.02,"detailed":0.0,"expert":0.0}'::jsonb,
  array[10, 11, 14, 15, 21, 22]::int[],
  array[1, 2, 3, 4, 5, 6]::int[],
  'lol_reactor'
),
(
  '진짜ㅋㅋ', 'worker', '30s', '영업직',
  array['잡담', '유머'],
  array['가벼움', '반응러'],
  array['진짜 ㅋㅋ', '이건 못 참지', '와 개웃김'],
  'medium', 'low', 'positive',
  'low', '진짜 ㅋㅋ로 시작해서 진짜 ㅋㅋ로 끝.',
  array['humor'],
  '{"openers":["진짜 ㅋㅋ","못 참지","와"],"closers":["ㅋㅋ","개웃김","ㅇㅈ"],"quirks":["진짜 ㅋㅋ 남발","짧은 반응"],"vocabulary_level":"low","typo_rate":0.06,"emoji_rate":0.1}'::jsonb,
  '{"quick":0.85,"casual":0.13,"normal":0.02,"detailed":0.0,"expert":0.0}'::jsonb,
  array[13, 14, 19, 20, 21]::int[],
  array[1, 2, 3, 4, 5, 6]::int[],
  'lol_reactor'
),
(
  '이거ㅋㅋ저장', 'worker', '20s', '마케터',
  array['밈', '저장'],
  array['웃음', '공감'],
  array['이거 저장', '레전드 ㅋㅋ', '웃겨서 돌아봤음'],
  'medium', 'medium', 'positive',
  'low', '재밌는 댓글 만나면 캡쳐하는 수집가.',
  array['humor'],
  '{"openers":["이거","레전드","돌아봤음"],"closers":["저장","ㅋㅋ","ㅇㅈ"],"quirks":["밈 수집","짧은 반응"],"vocabulary_level":"low","typo_rate":0.08,"emoji_rate":0.15}'::jsonb,
  '{"quick":0.80,"casual":0.18,"normal":0.02,"detailed":0.0,"expert":0.0}'::jsonb,
  array[12, 13, 19, 20, 21, 22]::int[],
  array[1, 2, 3, 4, 5, 6]::int[],
  'lol_reactor'
),
(
  'ㅇㅈ요정', 'worker', '30s', '직장인',
  array['공감', '잡담'],
  array['동의', '웃음'],
  array['ㅇㅈ', 'ㅇㅈㅇㅈ', '백번 ㅇㅈ ㅋㅋ'],
  'medium', 'medium', 'positive',
  'low', 'ㅇㅈ 외엔 할 말 없는 유형.',
  array['humor'],
  '{"openers":["ㅇㅈ","백번","ㅋㅋ"],"closers":["ㅇㅈ","ㅋㅋ","~임"],"quirks":["ㅇㅈ 남발","동의만"],"vocabulary_level":"low","typo_rate":0.05,"emoji_rate":0.1}'::jsonb,
  '{"quick":0.85,"casual":0.13,"normal":0.02,"detailed":0.0,"expert":0.0}'::jsonb,
  array[12, 13, 19, 20, 21, 22, 23]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'lol_reactor'
),
(
  '아진짜못참', 'student', '20s', '대학원생',
  array['유머', '연구'],
  array['웃음', '과장'],
  array['아 진짜 못참', 'ㅋㅋㅋ 교수님 오시는데', '이 스레드 왜이래'],
  'high', 'high', 'positive',
  'low', '학교에서 몰래 커뮤 보다 터지는 사람.',
  array['humor'],
  '{"openers":["아 진짜","ㅋㅋㅋ","이 스레드"],"closers":["ㅋㅋㅋ","못참","왜이래"],"quirks":["상황 중계","잡담에 반응"],"vocabulary_level":"low","typo_rate":0.12,"emoji_rate":0.25}'::jsonb,
  '{"quick":0.80,"casual":0.18,"normal":0.02,"detailed":0.0,"expert":0.0}'::jsonb,
  array[10, 11, 14, 15, 22, 23, 0]::int[],
  array[1, 2, 3, 4, 5, 6, 0]::int[],
  'lol_reactor'
),
(
  '웃기면살아남', 'worker', '40s', '중간관리자',
  array['잡담', '유머'],
  array['웃음', '공감'],
  array['웃기면 살아남음 ㅋㅋ', '이건 진짜 공감', '아 못참겠네'],
  'medium', 'low', 'positive',
  'mid', '부장 포지션인데 커뮤에선 ㅋㅋ만 남기는 사람.',
  array['humor'],
  '{"openers":["웃기면","이건 진짜","못참"],"closers":["ㅋㅋ","공감","~임"],"quirks":["ㅋ 최소화 존중","잡담에 반응"],"vocabulary_level":"mid","typo_rate":0.04,"emoji_rate":0.1}'::jsonb,
  '{"quick":0.75,"casual":0.22,"normal":0.03,"detailed":0.0,"expert":0.0}'::jsonb,
  array[9, 10, 13, 14, 20, 21, 22]::int[],
  array[1, 2, 3, 4, 5]::int[],
  'lol_reactor'
)
on conflict (nickname) do update set
  behavior_type = excluded.behavior_type,
  signature_patterns = excluded.signature_patterns,
  quality_weights = excluded.quality_weights;
